### ISSUE TITLE
update (or include) fallback variable in line with new SOE

### ISSUE THREAD

**Issue by conorvahland** [garysharp/EduHub.Data#2]
so now the CASESHV variable is no longer being used \\%CASESHV%\eduHub and i *think* stored on AFS instead.
suggest adding in the new format variables %SN%AFS%CN%

**Comment by garysharp** [comment]
Thanks Conor!

I've [added the new SOE format](https://github.com/garysharp/EduHub.Data/commit/fb38b636ebfc975ee7d75112ebd57a1b16f87aa6#diff-2) and prepared a [pre-release version](https://github.com/garysharp/EduHub.Data/releases/tag/v1.0.9). This has been tested at one site. If you (or anyone else) have the opportunity to test at another site let me know and I'll promote the release and publish to Nuget.

**Comment by garysharp** [comment]
These changes have been in place since [pre-release v1.0.9](https://github.com/garysharp/EduHub.Data/releases/tag/v1.0.9) and thus are included in latest stable release. Closing.
