### ISSUE TITLE
DFF file failing to parse

### ISSUE THREAD

**Issue by jamesr981** [garysharp/EduHub.Data#5]
Hi there,

I've been in Contact with the Eduhub team, and have been informed that the DFF.ACCOUNT_NUMBER can be up to 15 characters long.
So an Int32 would be unsuitable for this field as 15 characters long is too big.

**Comment by garysharp** [comment]
Thanks for reporting this issue.
The [current latest release](https://github.com/garysharp/EduHub.Data/releases/tag/v1.67.20) supports v67 (Jun 2022) of the schema. I can confirm that between schemas v69 (Apr 2023) and v70 (Jan 2024), the `ACCOUNT_NUMBER` field had its type changed from a 32-bit integer to an alpha-string up to 15 characters (as you suggested).

There are two components I need to be able to update EduHub.Data correctly - I have access to one.
I'll submit a request to the department for the other. If you don't see a new release of EduHub.Data within a few days feel free to reach out via email (its likely you have access to the component yourself).

**Comment by garysharp** [comment]
This is fixed with the [v1.70.21 release](https://github.com/garysharp/EduHub.Data/releases/tag/v1.70.21).
